### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by countback** [AmoseKang/DrQA_cn#1]
first of all， thanks for your code, have you try to train this model on chinese QA data set, if yes, can you tell me on which data set

**Comment by AmoseKang** [comment]
I trained with webQA provided by baidu, http://idl.baidu.com/WebQA.html

**Comment by AmoseKang** [comment]
`https://pan.baidu.com/s/1pL5ae4F   code: j5p2    `
Here is what i actually used after arrangement.

**Comment by DingkunLong** [comment]
thanks so much for your response, I'm new to the QA domain, If posiible for you to give me your e-mail address or Wechat id then ask some question on some pratice details,

**Comment by countback** [comment]
I try to run the code with the dataset(BAIDU-webqa), but i get some errors

**Comment by AmoseKang** [comment]
123kzj@gmail.com ... 说中文就好了，我也是刚学这些东西..
