### ISSUE TITLE
请问这个是drqa的中文版吗？ 

### ISSUE THREAD

**Issue by hdray123** [AmoseKang/DrQA_cn#2]
它的分词器能识别中文的ner和pos吗？

**Comment by hdray123** [comment]
我使用了你的数据集跑了 然后出现了 缺少drqa/features/zh_dict.json 请问这相当于英文的单词转300B向量的embeddings/glove.840B.300d文件吗

**Comment by AmoseKang** [comment]
中文pos是支持的，ner我是用了其他内容来代替…  那个dict文件是中英翻译用的，将中文的英文翻译作为ner tag。 我最近会再整理一遍…

**Comment by AmoseKang** [comment]
请不要用这个跑英文模型的内容，很多地方我更改了还没有测试过，我稍后会上传相关训练文件。

**Comment by hdray123** [comment]
谢谢你的解答和帮助  希望能写个readme 写一些中文预处理 训练 交互的步骤
关于这个中文跑出来的模型与英文的模型相比F1和EM是否有较大的差距？  @AmoseKang
